language: node_js
node_js:
    - "stable"
services:
    - docker

before_install:
    - docker build -t vamsi/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true vamsi/docker-react npm run test -- --coverage
